dhcpdump: Fix strsep() feature test
Use the official _BSD_SOURCE feature test macro instead of the meaningless
HAVE_STRSEP macro in order to detect the availability of strsep().

This allows toolchains supporting strsep() to use it instead of the custom
implementation from dhcpdump, which also avoids the following error with some
toolchains:

  In file included from dhcpdump.c:30:0:
  dhcpdump.c: At top level:
  strsep.c:65:23: error: register name not specified for ‘delim’
    register const char *delim;
                         ^

Signed-off-by: Benoît Thébaudeau <benoit.thebaudeau@advansee.com>